import { useState, type FormEvent } from "react";
import { Navigate, useLocation } from "react-router-dom";
import { Crown, Loader2, Lock, Mail } from "lucide-react";
import { useAuth } from "../lib/authContext";

export default function LoginPage(){
  const {user,login,loginError}=useAuth(); const location=useLocation(); const [email,setEmail]=useState(""); const [password,setPassword]=useState(""); const [loading,setLoading]=useState(false);
  if(user){const from=(location.state as {from?:Location})?.from?.pathname; return <Navigate to={from??"/panel"} replace/>}
  async function submit(e:FormEvent){e.preventDefault();setLoading(true);await login(email,password);setLoading(false)}
  return <div className="flex min-h-screen items-center justify-center bg-background px-4"><div className="w-full max-w-[420px]"><div className="mb-7 text-center"><div className="mx-auto mb-4 flex h-12 w-12 items-center justify-center rounded-xl bg-primary text-black"><Crown className="h-6 w-6"/></div><h1 className="text-2xl font-black">DJGABO <span className="text-primary">KARAOKE VIP</span></h1><p className="mt-2 text-[13px] text-muted-foreground">Accede a tus actualizaciones, paquetes y contenido exclusivo.</p></div><form onSubmit={submit} className="space-y-4 rounded-[10px] border border-white/[0.06] bg-card p-6 shadow-card"><div><label className="mb-1.5 block text-[12px] font-medium text-muted-foreground">Correo electrónico</label><div className="relative"><Mail className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground"/><input type="email" required autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="tu@correo.com" className="h-11 w-full rounded-md border border-white/[0.08] bg-secondary pl-10 pr-3 text-[13px] outline-none focus:border-primary/50"/></div></div><div><label className="mb-1.5 block text-[12px] font-medium text-muted-foreground">Contraseña</label><div className="relative"><Lock className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground"/><input type="password" required autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="••••••••" className="h-11 w-full rounded-md border border-white/[0.08] bg-secondary pl-10 pr-3 text-[13px] outline-none focus:border-primary/50"/></div></div>{loginError&&<p className="rounded-md bg-danger/10 px-3 py-2 text-[12px] text-danger">{loginError}</p>}<button disabled={loading} className="flex h-11 w-full items-center justify-center rounded-md bg-primary text-[13px] font-semibold text-black hover:brightness-95 disabled:opacity-50">{loading?<><Loader2 className="mr-2 h-4 w-4 animate-spin"/>Ingresando...</>:"Ingresar"}</button></form></div></div>
}
