import { Check, FolderOpen } from "lucide-react";
import { VipShell } from "../components/VipShell";

const packs = [
 {name:"Basic",price:"49",storage:"150 GB",desc:"Perfecto para cantar en casa y reuniones pequeñas.",items:["10.000 Karaokes español MP4","4.000 Karaokes inglés MP4","Géneros variados"]},
 {name:"Pro",price:"249",storage:"300 GB",featured:true,desc:"Ideal para DJs y fiestas grandes o eventos.",items:["28.000 Karaokes español MP3+G","4.000 Karaokes inglés MP3+G","5.000 Top Hits 2026-2021","Reproductor Karaoke Pro","Buscador Karaoke Pro","6 meses de actualizaciones GRATIS"]},
 {name:"Premium",price:"349",storage:"800 GB",desc:"Ideal para bares y karaokes. Toda la colección y actualizaciones constantes.",items:["28.000 Karaokes español MP3+G","28.000 Karaokes inglés MP3+G","5.000 Top Hits 2026-2021","Multilingüe + Salsa y Cumbia GOLD","Herramientas Pro","1 año de actualizaciones GRATIS"]},
];
export default function PackagesPage(){return <VipShell><div className="space-y-5">
  <div><div className="mb-2 inline-flex items-center gap-1.5 font-mono text-[11px] font-bold tracking-wider text-primary"><FolderOpen className="h-3.5 w-3.5"/> PACKS KARAOKE</div><h1 className="max-w-3xl text-2xl font-black leading-tight">Paquetes karaoke para Fiesta en casa, Eventos o Bares</h1><p className="mt-2 max-w-3xl text-[13px] leading-relaxed text-muted-foreground">Colecciones karaoke ordenadas y catalogadas en formatos MP4 y CDG, con herramientas profesionales DJGABO.</p></div>
  <div className="border-t border-white/[0.06]" />
  <div className="flex flex-wrap justify-center gap-5">{packs.map(p=><div key={p.name} className={`relative flex w-full max-w-[320px] flex-col rounded-[10px] bg-card p-5 ${p.featured?"border border-primary":"border border-white/[0.06]"}`}>{p.featured&&<div className="absolute -top-2.5 left-1/2 -translate-x-1/2 rounded-full bg-primary px-2.5 py-0.5 font-mono text-[10px] font-bold text-black">MÁS POPULAR</div>}<div className="text-[15px] font-bold">{p.name}</div><div className="mt-1 text-[12px] text-muted-foreground">{p.desc}</div><div className="my-4 flex items-end gap-2"><span className="font-mono text-3xl font-black">${p.price}</span><span className="pb-1 font-mono text-[11px] text-muted-foreground">USD • {p.storage}</span></div><ul className="mb-5 flex-1 space-y-2">{p.items.map(i=><li key={i} className="flex gap-2 text-[12px]"><Check className="mt-0.5 h-3.5 w-3.5 shrink-0 text-primary"/>{i}</li>)}</ul><button className={`${p.featured?"bg-primary text-black":"border border-white/[0.08] bg-secondary"} rounded-md py-2.5 text-[13px] font-semibold`}>Consultar paquete</button></div>)}</div>
</div></VipShell>}
