import { Check, Crown } from "lucide-react";
import { Link } from "react-router-dom";
import { VipShell } from "../components/VipShell";
const plans=[
 {name:"1 Mes",price:"29.99",period:"/mes",items:["3 descargas de contenido VIP","Acceso a 3 carpetas de actualizaciones","3 Karaokes a pedido GRATIS en CDG","1 Guarda en tu Dropbox"]},
 {name:"6 Meses",price:"109.99",period:"/6 meses",featured:true,items:["Acceso a todas las actualizaciones 2026","6 meses de actualizaciones nuevas","Nuevos karaokes diarios","5 Karaokes a pedido GRATIS por mes","Descargas ilimitadas 24/7"]},
 {name:"1 Año",price:"169.99",period:"/año",items:["Acceso a actualizaciones 2026-2012","12 meses de actualizaciones nuevas","Nuevos karaokes diarios","15 Karaokes a pedido GRATIS por mes","Descargas ilimitadas 24/7"]},
];
export default function PlansPage(){return <VipShell><div className="space-y-5"><div><div className="mb-2 inline-flex items-center gap-1.5 font-mono text-[11px] font-bold tracking-wider text-primary"><Crown className="h-3.5 w-3.5"/> MEMBRESÍA VIP</div><h1 className="text-2xl font-black">Planes y Precios — Karaokes DJGABO</h1><p className="mt-2 max-w-3xl text-[13px] leading-relaxed text-muted-foreground">Acceso a colecciones, paquetes y nuevos lanzamientos. Elige el periodo que mejor se adapte a tu negocio.</p></div><div className="border-t border-white/[0.06]"/><div className="text-center"><h2 className="text-lg font-bold">Actualiza tu contenido con karaokes de alta calidad.</h2><p className="mt-1 text-[13px] text-muted-foreground">Mejora desde hoy tus sesiones y sorprende a todos.</p></div><div className="flex flex-wrap justify-center gap-5">{plans.map(p=><div key={p.name} className={`relative flex w-full max-w-[270px] flex-col rounded-[10px] bg-card p-5 ${p.featured?"border border-primary":"border border-white/[0.06]"}`}>{p.featured&&<div className="absolute -top-2.5 left-1/2 -translate-x-1/2 rounded-full bg-primary px-2.5 py-0.5 font-mono text-[10px] font-bold text-black">MÁS POPULAR</div>}<div className="mb-1 text-[13px] font-semibold">{p.name}</div><div className="mb-4 flex items-baseline gap-1"><span className="font-mono text-2xl font-black">${p.price}</span><span className="font-mono text-[12px] text-muted-foreground">USD {p.period}</span></div><ul className="mb-5 flex-1 space-y-1.5">{p.items.map(i=><li key={i} className="flex items-start gap-2 text-[12px]"><Check className="mt-0.5 h-3.5 w-3.5 shrink-0 text-primary"/>{i}</li>)}</ul><button className={`${p.featured?"bg-primary text-black":"border border-white/[0.06] bg-secondary"} rounded-md py-2.5 text-[13px] font-semibold`}>Suscribirme</button></div>)}</div><div className="text-center"><Link to="/panel" className="text-[13px] text-primary hover:underline">← Volver al panel</Link></div></div></VipShell>}
